In [1]:
#Answer-1

import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
array_3x3 = np.random.randint(1, 101, size=(3, 3))

# Interchange its rows and columns (transpose the array)
transposed_array = array_3x3.T

# Display the original and transposed arrays
print("Original Array:\n", array_3x3)
print("Transposed Array:\n", transposed_array)


Original Array:
 [[40 43 82]
 [85 10 42]
 [33 63 44]]
Transposed Array:
 [[40 85 33]
 [43 10 63]
 [82 42 44]]


In [2]:
#Answer-2

import numpy as np

# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Reshape it into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)

# Display the arrays
print("1D Array:\n", array_1d)
print("Reshaped to 2x5 Array:\n", array_2x5)
print("Reshaped to 5x2 Array:\n", array_5x2)


1D Array:
 [0 1 2 3 4 5 6 7 8 9]
Reshaped to 2x5 Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Reshaped to 5x2 Array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [3]:
#Answer-3

import numpy as np

# Create a 4x4 NumPy array with random float values
array_4x4 = np.random.rand(4, 4)

# Add a border of zeros around the 4x4 array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

# Display the original and the new array
print("Original 4x4 Array:\n", array_4x4)
print("6x6 Array with Border of Zeros:\n", array_with_border)




Original 4x4 Array:
 [[0.23995783 0.9121459  0.23194613 0.45006806]
 [0.99406648 0.09120055 0.78928911 0.1637252 ]
 [0.63114244 0.27793576 0.65494061 0.83453168]
 [0.23355232 0.77517536 0.45584204 0.47482344]]
6x6 Array with Border of Zeros:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.23995783 0.9121459  0.23194613 0.45006806 0.        ]
 [0.         0.99406648 0.09120055 0.78928911 0.1637252  0.        ]
 [0.         0.63114244 0.27793576 0.65494061 0.83453168 0.        ]
 [0.         0.23355232 0.77517536 0.45584204 0.47482344 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [4]:
#Answer-4

import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array_integers = np.arange(10, 61, 5)

# Display the resulting array
print("Array of integers from 10 to 60 with a step of 5:\n", array_integers)


Array of integers from 10 to 60 with a step of 5:
 [10 15 20 25 30 35 40 45 50 55 60]


In [5]:
#Answer-5

import numpy as np

# Create a NumPy array of strings
string_array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(string_array)     # Uppercase
lowercase_array = np.char.lower(string_array)     # Lowercase
titlecase_array = np.char.title(string_array)     # Title case

# Display the transformed arrays
print("Original Array:\n", string_array)
print("Uppercase:\n", uppercase_array)
print("Lowercase:\n", lowercase_array)
print("Title Case:\n", titlecase_array)


Original Array:
 ['python' 'numpy' 'pandas']
Uppercase:
 ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase:
 ['python' 'numpy' 'pandas']
Title Case:
 ['Python' 'Numpy' 'Pandas']


In [6]:
#Answer-6

import numpy as np

# Create a NumPy array of words
words_array = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_words_array = np.char.join(' ', words_array)

# Display the original and the modified arrays
print("Original Array:\n", words_array)
print("Array with Spaces Between Characters:\n", spaced_words_array)



Original Array:
 ['python' 'numpy' 'pandas']
Array with Spaces Between Characters:
 ['p y t h o n' 'n u m p y' 'p a n d a s']


In [7]:
#Answer-7

import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[10, 20, 30], [40, 50, 60]])
array2 = np.array([[1, 2, 3], [4, 5, 6]])

# Perform element-wise operations
addition = np.add(array1, array2)        # Element-wise addition
subtraction = np.subtract(array1, array2) # Element-wise subtraction
multiplication = np.multiply(array1, array2) # Element-wise multiplication
division = np.divide(array1, array2)     # Element-wise division

# Display the results
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("\nElement-wise Addition:\n", addition)
print("Element-wise Subtraction:\n", subtraction)
print("Element-wise Multiplication:\n", multiplication)
print("Element-wise Division:\n", division)


Array 1:
 [[10 20 30]
 [40 50 60]]
Array 2:
 [[1 2 3]
 [4 5 6]]

Element-wise Addition:
 [[11 22 33]
 [44 55 66]]
Element-wise Subtraction:
 [[ 9 18 27]
 [36 45 54]]
Element-wise Multiplication:
 [[ 10  40  90]
 [160 250 360]]
Element-wise Division:
 [[10. 10. 10.]
 [10. 10. 10.]]


In [8]:
#Answer-8

import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

# Display the identity matrix and its diagonal elements
print("5x5 Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:\n", diagonal_elements)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements:
 [1. 1. 1. 1. 1.]


In [9]:
#Answer-9

import numpy as np

# Function to check if a number is prime
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1001, size=100)

# Find all prime numbers in the array
prime_numbers = np.array([num for num in random_array if is_prime(num)])

# Display the random array and the prime numbers
print("Random Array:\n", random_array)
print("Prime Numbers in the Array:\n", prime_numbers)




Random Array:
 [400 201 479 506 574  52 252 260 675 975 405   7 912 361 467 152 230 225
 288 419   5 212 113 206 901 564 732 404 623 806 406 367  19 647  36 218
 842 118 935 415 598  33 179 694 783 679 821 641 363 450 830 217 983 552
  61 455 709 858 265 283 733 318 940 483 886 832 487 380 149 327 138 372
 583  32 731 920 799 487 719 406 866 480 116  58 304 255 734 118 579 523
 815 184 381 315 575 331 375 160 303 739]
Prime Numbers in the Array:
 [479   7 467 419   5 113 367  19 647 179 821 641 983  61 709 283 733 487
 149 487 719 523 331 739]


In [10]:
#Answer-10

import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
daily_temperatures = np.random.randint(15, 35, size=30)  # Temperatures between 15 and 35 degrees

# Reshape the array to have 4 weeks (7 days per week, and last week with 2 days in this case)
weeks = np.split(daily_temperatures[:28], 4)  # First 4 weeks with 7 days
last_week = daily_temperatures[28:]  # Last week (remaining 2 days)

# Calculate weekly averages
weekly_averages = [np.mean(week) for week in weeks] + [np.mean(last_week)]

# Display the daily temperatures and weekly averages
print("Daily Temperatures for the Month:\n", daily_temperatures)
print("\nWeekly Averages:")
for i, avg in enumerate(weekly_averages, 1):
    print(f"Week {i}: {avg:.2f}")
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
daily_temperatures = np.random.randint(15, 35, size=30)  # Temperatures between 15 and 35 degrees

# Reshape the array to have 4 weeks (7 days per week, and last week with 2 days in this case)
weeks = np.split(daily_temperatures[:28], 4)  # First 4 weeks with 7 days
last_week = daily_temperatures[28:]  # Last week (remaining 2 days)

# Calculate weekly averages
weekly_averages = [np.mean(week) for week in weeks] + [np.mean(last_week)]

# Display the daily temperatures and weekly averages
print("Daily Temperatures for the Month:\n", daily_temperatures)
print("\nWeekly Averages:")
for i, avg in enumerate(weekly_averages, 1):
    print(f"Week {i}: {avg:.2f}")


Daily Temperatures for the Month:
 [21 21 20 28 34 16 30 27 18 16 34 19 15 31 24 26 27 28 22 34 24 18 22 29
 18 19 27 34 20 29]

Weekly Averages:
Week 1: 24.29
Week 2: 22.86
Week 3: 26.43
Week 4: 23.86
Week 5: 24.50
Daily Temperatures for the Month:
 [27 27 34 20 20 34 25 19 30 26 29 23 26 30 19 34 16 23 34 21 27 18 16 30
 34 25 32 31 29 33]

Weekly Averages:
Week 1: 26.71
Week 2: 26.14
Week 3: 24.86
Week 4: 26.57
Week 5: 31.00
